name:                sdl2-image
version:             2.1.0.0
git:                 https://gitlab.homotopic.tech/haskell/sdl2-image
bug-reports:         https://gitlab.homotopic.tech/haskell/sdl2-image/issues
license:             MIT
author:
- Cai Lei
- Siniša Biđin
- Daniel Firth
maintainer:
- Siniša Biđin <sinisa@bidin.eu>
- Daniel Firth <dan.firth@homotopic.tech>
copyright:
- 2014 Cal Lei
- 2015 Siniša Biđin
- 2021 Daniel Firth

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Haskell bindings to SDL2_image
category:            Graphics, Foreign, Image

dependencies:
- base >= 4.9 && < 5
- sdl2 >= 2.0.0
- text >= 1.1.0.0

library:
  dependencies:
  - bytestring >= 0.10.4.0
  - template-haskell >= 2.10
  source-dirs: src
  verbatim:
    autogen-modules:
      Paths_sdl2_image

pkg-config-dependencies:
- sdl2 >= 2.0.3
- SDL2_image >= 1.0.1

extra-libraries:
- SDL2_image

executables:
  sdl2-image-example:
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    source-dirs: example
    main: Main.hs
    dependencies:
    - sdl2-image

ghc-options:
- -Weverything
- -Wno-all-missed-specialisations
- -Wno-implicit-prelude
- -Wno-missing-safe-haskell-mode
- -Wno-prepositive-qualified-module
- -Wno-missing-import-lists
- -Wno-safe
- -Wno-unsafe
